tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "shopify/shopify"
brew "asdf"
brew "fish"
brew "gawk" # required by asdf node.js plugin
brew "gh"
brew "git"
brew "gnupg"
brew "htop"
brew "mas"
brew "ruby" # required by shopify-cli
brew "shopify-cli"
brew "vercel-cli"
brew "yadm"
cask "1password"
cask "docker"
cask "elgato-stream-deck"
cask "fantastical"
cask "figma"
cask "firefox"
cask "font-caskaydia-cove-nerd-font"
cask "google-chrome"
cask "iterm2"
cask "little-snitch"
cask "logitech-options"
cask "notion"
cask "rectangle"
cask "slack"
cask "stats"
cask "visual-studio-code"
cask "zoom"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
