padding: 1
end: 
divider: 
fg: white
bg: black
lines_above: 1
modules:
- failure_bg: '#bb4444'
  failure_fg: '#ffffff'
  show_success: true
  success_bg: '#000000'
  success_fg: '#ffffff'
  success_output: 
  type: exitcode
- bg: '#ffffff'
  fg: '#334488'
  threshold: 3s
  type: duration
- bg: '#334488'
  fg: '#aaaaaa'
  label:  %s
  max_depth: 3
  type: cwd
- bg: '#393939'
  fg: '#777777'
  type: git
